### ISSUE TITLE
Дизайн стартового экрана

### ISSUE THREAD

**Issue by sashachernyakova** [sashachernyakova/Java_practice_2023#3]

**Comment by Olesya-Khulap** [comment]
![Title Page (1)](https://github.com/sashachernyakova/Java_practice_2023/assets/69355717/f3999d8c-a015-46ec-af3d-469dce1f15a5)

**Comment by Olesya-Khulap** [comment]
![Title Page (2)](https://github.com/sashachernyakova/Java_practice_2023/assets/69355717/05f096c5-efc6-4769-a03a-722ab65c52cd)
